#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

RELEASE_FILE=/etc/bareon-release

SCRIPTDIR=$(dirname $0)
install-packages python-setuptools python-pip python-dev

if [ -d /tmp/bareon/.git ] ; then
    cd /tmp/bareon
    pip install --upgrade setuptools
    pip install -r requirements.txt && python setup.py install

    pip freeze | grep bareon > $RELEASE_FILE
    echo "Source-based bareon installation. Git log:" >> $RELEASE_FILE
    cat changelog >> $RELEASE_FILE

    cd /
else
    install-packages bareon

    pip freeze | grep bareon > $RELEASE_FILE
    echo "RPM-based bareon installation. RPM info:" >> $RELEASE_FILE
    rpm -qi bareon >> $RELEASE_FILE
fi

install -D -g root -o root -m 0600 ${SCRIPTDIR}/files.ironic/etc/ssh/sshd_config /etc/ssh/sshd_config
install -D -g root -o root -m 0664 ${SCRIPTDIR}/files.ironic/etc/network /etc/sysconfig/network
install -D -g root -o root -m 0644 ${SCRIPTDIR}/files.ironic/usr/lib/systemd/system/ironic-callback.service /usr/lib/systemd/system/ironic-callback.service
install -D -g root -o root -m 0644 ${SCRIPTDIR}/files.ironic/etc/bareon/bareon.conf /etc/bareon/bareon.conf

install -d -g root -o root -m 0700 /root/.ssh
if [ -n "${DIB_BAREON_ROOT_PASSWORD:-}" ]; then
    echo "root:$DIB_BAREON_ROOT_PASSWORD" | chpasswd
fi
if [ -f /tmp/bareon-build/inject-ssh-key.pub ]; then
    (umask 0077; touch /root/.ssh/authorized_keys)
    cat "/tmp/bareon-build/inject-ssh-key.pub" > /root/.ssh/authorized_keys
fi

systemctl enable ironic-callback.service
